packages:
  - 'apps/*'
  - 'packages/*'
allowBuilds:
  '@prisma/client': false
  '@tailwindcss/oxide': set this to true or false
  better-sqlite3: false
  esbuild: true
  sharp: true
onlyBuiltDependencies:
  - esbuild
