export { Model, RegisterModel, createModel, type ModelConfig } from './model.js'
export { QueryBuilder } from './query-builder.js'
export { RelationshipLoader } from './relationships.js'
export { Migration, MigrationRunner } from './migrations.js'
export { configureDatabase, getDatabase, type DatabaseConfig } from './database.js'
export { createDatabaseHandle, createDatabaseHandle as databaseHook, initDb } from './hooks.js'
export type { OmniSvelteLocals, QueryHelpers } from './hooks.js'
// export { generateDrizzleConfig, cleanupDrizzleConfig } from './drizzle-config-generator.js'
