import { describe, it, expect, vi, beforeEach } from 'vitest';
import { existsSync } from 'fs';
import { resolve } from 'path';

// Minimal fake omniConfig matching the schema output config
const fakeConfig = {
    schema: {
        output: {
            model: { path: 'src/lib/db/models', format: 'per-schema' as const },
            drizzle: { path: 'src/lib/db/server/schema.ts', format: 'single-file' as const },
            zod: { path: 'src/lib/db/validation', format: 'per-schema' as const },
        }
    }
};

const ROOT = 'C:/fake-project';

/**
 * Utility: simulate what resolveId does in the plugin
 */
const VIRTUAL_PREFIX = '\0virtual:omni:';
function resolveId(id: string): string | undefined {
    if (id === '$models' || id === '$schema' || id === '$validation' || id === '$db') {
        return VIRTUAL_PREFIX + id.slice(1);
    }
    // Sub-path: pass through to alias
    return undefined;
}

/**
 * Utility: simulate what load() does (simplified)
 */
function loadDb(): string {
    return `import { database } from 'omni-svelte/database';\nexport { database as db };\nexport default database;`;
}

function loadSchema(schemaPath: string): string {
    return `export * from '${schemaPath.replace(/\\/g, '/')}';`;
}

function loadModels(modelsPath: string, files: string[], format: 'per-schema' | 'single-file'): string {
    if (format === 'single-file') return `export * from '${modelsPath}';`;
    if (!files.length) return `// No model files found in ${modelsPath}`;
    return files.map(f => `export * from '${modelsPath}/${f}';`).join('\n');
}

function loadValidation(zodPath: string, files: string[], format: 'per-schema' | 'single-file'): string {
    if (format === 'single-file') return `export * from '${zodPath}';`;
    if (!files.length) return `// No validation files found in ${zodPath}`;
    return files.map(f => `export * from '${zodPath}/${f}';`).join('\n');
}

/**
 * Utility: simulate omni-env.d.ts content generation
 * Must match the real plugin's logic in packages/core/src/vite/index.ts.
 * Uses $lib/... aliases (non-relative) because TypeScript forbids relative
 * imports inside ambient `declare module` blocks.
 */
function generateDtsContent(config: typeof fakeConfig, root: string): string {
    const out = config.schema.output;
    const libDir = resolve(root, 'src/lib');

    const modelsAbsPath = resolve(root, out.model.path);
    const drizzleAbsPath = resolve(root, out.drizzle.path);
    const zodAbsPath = resolve(root, out.zod.path);

    const toLibAlias = (absPath: string) =>
        '$lib/' + absPath.replace(libDir, '').replace(/^[\\/]/, '').replace(/\\/g, '/').replace(/\.ts$/, '');

    const modelsAlias = toLibAlias(modelsAbsPath);
    const drizzleAlias = toLibAlias(drizzleAbsPath);
    const zodAlias = toLibAlias(zodAbsPath);

    const modelsIndex = out.model.format === 'single-file' ? modelsAlias : `${modelsAlias}/index`;
    const zodIndex = out.zod.format === 'single-file' ? zodAlias : `${zodAlias}/index`;

    return [
        `// Auto-generated by omni-svelte. Do not edit manually.`,
        `// Re-generated only when omniConfig.schema.output paths change.`,
        `// NOTE: ambient declare modules must use non-relative specifiers (TS rule).`,
        `//       All paths below use the $lib alias resolved by SvelteKit's tsconfig.`,
        ``,
        `// SERVER-ONLY: Models (contain database queries)`,
        `declare module '$models' { export * from '${modelsIndex}'; }`,
        `declare module '$models/*' { const mod: any; export = mod; }`,
        ``,
        `// SERVER-ONLY: Drizzle schema table definitions`,
        `declare module '$schema' { export * from '${drizzleAlias}'; }`,
        ``,
        `// SERVER-ONLY: Raw database connection`,
        `declare module '$db' {`,
        `  import type { PostgresJsDatabase } from 'drizzle-orm/postgres-js';`,
        `  export const db: PostgresJsDatabase;`,
        `}`,
        ``,
        `// UNIVERSAL: Zod validation schemas (safe for client and server)`,
        `declare module '$validation' { export * from '${zodIndex}'; }`,
        `declare module '$validation/*' { const mod: any; export = mod; }`,
    ].join('\n');
}

// ─────────────────────────────────────────────────────────────
describe('plugin_omni_virtual_aliases – resolveId', () => {
    it('resolves $models to virtual:omni:models', () => {
        expect(resolveId('$models')).toBe('\0virtual:omni:models');
    });

    it('resolves $schema to virtual:omni:schema', () => {
        expect(resolveId('$schema')).toBe('\0virtual:omni:schema');
    });

    it('resolves $validation to virtual:omni:validation', () => {
        expect(resolveId('$validation')).toBe('\0virtual:omni:validation');
    });

    it('resolves $db to virtual:omni:db', () => {
        expect(resolveId('$db')).toBe('\0virtual:omni:db');
    });

    it('passes through sub-path imports ($models/posts.model) unmodified', () => {
        expect(resolveId('$models/posts.model')).toBeUndefined();
    });
});

// ─────────────────────────────────────────────────────────────
describe('plugin_omni_virtual_aliases – load barrel generation', () => {
    const modelsRoot = `${ROOT}/src/lib/db/models`;
    const zodRoot = `${ROOT}/src/lib/db/validation`;
    const drizzleRoot = `${ROOT}/src/lib/db/server/schema.ts`;

    it('generates correct $db export', () => {
        const code = loadDb();
        expect(code).toContain("import { database } from 'omni-svelte/database'");
        expect(code).toContain("export { database as db }");
    });

    it('generates correct $schema re-export', () => {
        const code = loadSchema(drizzleRoot);
        expect(code).toContain(`export * from '${drizzleRoot.replace(/\\/g, '/')}'`);
    });

    it('generates per-schema barrel for $models', () => {
        const files = ['users.model.ts', 'posts.model.ts'];
        const code = loadModels(modelsRoot, files, 'per-schema');
        expect(code).toContain('users.model.ts');
        expect(code).toContain('posts.model.ts');
    });

    it('generates single-file re-export for $models', () => {
        const code = loadModels(modelsRoot, [], 'single-file');
        expect(code).toBe(`export * from '${modelsRoot}';`);
    });

    it('generates per-schema barrel for $validation', () => {
        const files = ['users.validation.ts', 'posts.validation.ts'];
        const code = loadValidation(zodRoot, files, 'per-schema');
        expect(code).toContain('users.validation.ts');
        expect(code).toContain('posts.validation.ts');
    });

    it('returns placeholder comment when models dir is empty', () => {
        const code = loadModels(modelsRoot, [], 'per-schema');
        expect(code).toContain('No model files found');
    });
});

// ─────────────────────────────────────────────────────────────
describe('plugin_omni_virtual_aliases – omni-env.d.ts smart diff', () => {
    it('generates valid d.ts content with correct module declarations', () => {
        const content = generateDtsContent(fakeConfig, ROOT);
        expect(content).toContain(`declare module '$models'`);
        expect(content).toContain(`declare module '$schema'`);
        expect(content).toContain(`declare module '$validation'`);
        expect(content).toContain(`declare module '$db'`);
    });

    it('uses $lib/... aliases — never relative ./ paths inside declare module blocks', () => {
        // TypeScript forbids relative imports inside ambient declare module declarations.
        // Every export * from '...' inside a declare module must be a non-relative specifier.
        const content = generateDtsContent(fakeConfig, ROOT);
        const declareModuleBlocks = content.match(/declare module '[^']+' \{[^}]+\}/gs) ?? [];
        for (const block of declareModuleBlocks) {
            const exportLines = block.match(/export \* from '[^']+'/g) ?? [];
            for (const line of exportLines) {
                expect(line).not.toMatch(/from '\.\//);
            }
        }
        // Positively assert $lib prefix is used for real paths
        expect(content).toContain(`from '$lib/`);
    });

    it('produces same output for same config (idempotent - would not trigger write)', () => {
        const first = generateDtsContent(fakeConfig, ROOT);
        const second = generateDtsContent(fakeConfig, ROOT);
        expect(first.trim()).toBe(second.trim());
    });
});
