import { existsSync, readFileSync, writeFileSync } from 'fs';
import { resolve, relative, dirname } from 'path';
import type { SchemaConfig } from '../schema/types.js';
import type { OmniConfig } from '../types.js';

const MARKER = '// Auto-generated by omni-svelte.';

/**
 * Returns the POSIX-style schema path or glob to use in drizzle.config.ts.
 *
 * - single-file format → bare relative path  (e.g. `./src/lib/db/server/schema.ts`)
 * - per-schema format  → directory glob       (e.g. `./src/lib/db/server/**\/*.ts`)
 */
function resolveSchemaGlob(
	root: string,
	drizzleOutput: NonNullable<SchemaConfig['output']>['drizzle']
): string {
	if (!drizzleOutput?.path) return './src/lib/db/server/schema.ts';

	const absPath = resolve(root, drizzleOutput.path);
	const relPath = './' + relative(root, absPath).replace(/\\/g, '/');

	const format = drizzleOutput.format ?? 'single-file';

	if (format === 'per-schema') {
		// It's a directory — add a glob so Drizzle Kit picks up all .ts files inside
		const dir = relPath.endsWith('/') ? relPath : relPath + '/';
		return `${dir}**/*.ts`;
	}

	// single-file — return as-is
	return relPath;
}

/**
 * Returns the migrations output directory.
 * Defaults to `./drizzle` but can be overridden via `schemaConfig.output.drizzleConfig.out`.
 */
function resolveMigrationsOut(schemaConfig: SchemaConfig): string {
	return (schemaConfig.output as any)?.drizzleConfig?.out ?? './drizzle';
}

function resolveDialect(schemaConfig: SchemaConfig): string {
	return schemaConfig.generation?.drizzle?.dialect ?? 'postgresql';
}

/**
 * Build the full content of the drizzle.config.ts file.
 */
function buildDrizzleConfigContent(
	schemaGlob: string,
	migrationsOut: string,
	dialect: string,
	verbose = true,
	strict = true
): string {
	return [
		`${MARKER} Run \`pnpm dev\` to refresh.`,
		`// Source: svelte.config.js → omni.schema.output.drizzle`,
		`import { defineConfig } from 'drizzle-kit';`,
		``,
		`if (!process.env.DATABASE_URL) throw new Error('DATABASE_URL is not set');`,
		``,
		`export default defineConfig({`,
		`\tschema: '${schemaGlob}',`,
		`\tout: '${migrationsOut}',`,
		`\tdialect: '${dialect}',`,
		`\tdbCredentials: { url: process.env.DATABASE_URL },`,
		`\tverbose: ${verbose},`,
		`\tstrict: ${strict},`,
		`});`,
		``
	].join('\n');
}

/**
 * Generate or update `drizzle.config.ts` in the project root.
 *
 * - If the file does not exist → create it.
 * - If the file exists and starts with `MARKER` (was auto-generated) → rewrite if changed.
 * - If the file exists but was NOT auto-generated → warn and skip to avoid clobbering user edits.
 */
export async function generateDrizzleConfig(
	root: string,
	schemaConfig: SchemaConfig,
	omniConfig: OmniConfig
): Promise<void> {
	if (!schemaConfig.output?.drizzle) return;

	const configPath = resolve(root, 'drizzle.config.ts');
	const fallbackPath = resolve(root, 'drizzle.config.js');

	// Check if a user-managed (non-omni) config exists — if so, warn and skip
	for (const candidate of [configPath, fallbackPath]) {
		if (existsSync(candidate)) {
			const existing = readFileSync(candidate, 'utf-8');
			if (!existing.trimStart().startsWith(MARKER)) {
				if (schemaConfig.dev?.logLevel !== 'silent') {
					console.warn(
						`[omni-svelte] drizzle.config.ts exists but was not generated by omni-svelte.\n` +
							`  Add the marker "${MARKER}" as the first line to let omni-svelte manage it, or leave it as-is.`
					);
				}
				return;
			}
		}
	}

	const schemaGlob = resolveSchemaGlob(root, schemaConfig.output.drizzle);
	const migrationsOut = resolveMigrationsOut(schemaConfig);
	const dialect = resolveDialect(schemaConfig);
	const verbose = (schemaConfig.output as any)?.drizzleConfig?.verbose ?? true;
	const strict = (schemaConfig.output as any)?.drizzleConfig?.strict ?? true;

	const newContent = buildDrizzleConfigContent(schemaGlob, migrationsOut, dialect, verbose, strict);

	// Idempotency check — skip write if content is unchanged
	if (existsSync(configPath)) {
		const current = readFileSync(configPath, 'utf-8');
		if (current.trim() === newContent.trim()) return;
	}

	writeFileSync(configPath, newContent, 'utf-8');

	if (schemaConfig.dev?.logLevel !== 'silent') {
		console.log(`⚙️  [omni-svelte] Generated drizzle.config.ts (schema: ${schemaGlob})`);
	}
}

// ── Exports for unit testing ────────────────────────────────────────────────
export {
	resolveSchemaGlob,
	resolveMigrationsOut,
	resolveDialect,
	buildDrizzleConfigContent,
	MARKER
};
