
// Auto-generated by Omni Framework - DO NOT EDIT
export const generatedClientConfig = {
  baseURL: typeof window !== 'undefined' ? window.location.origin : '',
  basePath: '/api/auth',
};
export default generatedClientConfig;
    