
// Auto-generated by Omni Framework - DO NOT EDIT
import {
  twoFactor,
  jwt,
  openAPI,
  multiSession,
  organization,
  admin,
  magicLink,
  emailOTP
} from 'better-auth/plugins';
import { passkey } from 'better-auth/plugins/passkey';

export const config = {
  appName: 'My App',
  
  secret: process.env.BETTER_AUTH_SECRET || process.env.AUTH_SECRET,
  
  socialProviders: {
    github: {
      enabled: true,
    },
    google: {
      enabled: true,
    },
  },
  
  emailAndPassword: {
    enabled: true,
    requireEmailVerification: true,
    sendResetPasswordEmail: async (user, url, request) => {
    const { sendResetPasswordEmail } = await import('$pkg/emails');
    return sendResetPasswordEmail(user, url, request);
  },
    sendVerificationEmail: async (user, url, request) => {
    const { sendVerificationEmail } = await import('$pkg/emails');
    return sendVerificationEmail(user, url, request);
  },
  },
  
  session: {
    expiresIn: 2592000,
    updateAge: 86400,
  },
  
  
  
  
  
  
  
  advanced: {
    useSecureCookies: process.env.NODE_ENV === 'production',
    cookiePrefix: 'better-auth',
  },
  
  plugins: [
    magicLink({
      sendMagicLink: async ({ email, token, url }, request) => {
        const { sendMagicLink } = await import('$pkg/emails');
        return sendMagicLink({ email, token, url }, request);
      },
    }),
    emailOTP({
      sendVerificationOTP: async ({ email, otp, type }, request) => {
        const { sendVerificationOTP } = await import('$pkg/emails');
        return sendVerificationOTP({ email, otp, type }, request);
      },
    }),
    passkey(),
    admin(),
    organization(),
    multiSession(),
    openAPI(),
    jwt(),
    twoFactor()
  ],
};

export default config;
