// Auto-generated by omni-svelte. Do not edit manually.
// Re-generated only when omniConfig.schema.output paths change.
// NOTE: ambient declare modules must use non-relative specifiers (TS rule).
//       All paths below use the $lib alias resolved by SvelteKit's tsconfig.

// SERVER-ONLY: Models (contain database queries)
declare module '$models' {
	export * from '$lib/db/models/index';
}
declare module '$models/*' {
	const mod: any;
	export = mod;
}

// SERVER-ONLY: Drizzle schema table definitions
declare module '$schema' {
	export * from '$lib/db/server/schema';
}

// SERVER-ONLY: Raw database connection
declare module '$db' {
	import type { PostgresJsDatabase } from 'drizzle-orm/postgres-js';
	export const db: PostgresJsDatabase;
}

// UNIVERSAL: Zod validation schemas (safe for client and server)
declare module '$validation' {
	export * from '$lib/db/validation/index';
}
declare module '$validation/*' {
	const mod: any;
	export = mod;
}
